### PR TITLE
Docker UNIX Domain socket exposure scanning

### PR DESCRIPTION
**Pull request by brompwnie**
This pull request includes functionality to scan the host for access to the the Docker UNIX Domain socket.

screen shot 2019-02-08 at 16 48 56

### CODE REVIEW

**Comment by brompwnie** [comment]
Struggling to see where/why the build is failing :/ If anyone can point me in the right direction, I'll resolve it.

**Comment by tklauser** [comment]
@brompwnie it's failing because of `staticcheck` complaining about an unused variable in existing code (not a problem of your PR). This should be fixed as part of #17 once it gets merged.

**Comment by brompwnie** [comment]
@tklauser awesome thanks for the info, hopefully the merges happen soon.

**Comment by tklauser** [comment]
@brompwnie #17 was merged (thanks @jessfraz!) and this PR now needs a rebase. Then the Travis build should hopefully pass :smiley:

**Comment by brompwnie** [comment]
@tklauser awesome thanks for the ping! Looks like we are good to go :)

**Comment by jessfraz** [comment]
awesome thanks!

**Comment by brompwnie** [comment]
You're welcome 🎆

**Pull request merged**
